language: node_js
node_js:
  - 10.13.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - develop
deploy:
  provider: heroku
  api_key:
    secure: "BMRdHDymI7Jlc8+eyY+nyYma/ANpEV3Aq8PSZaspiB2pnbPWV3Go/fy1l3c2t0BfWcfTT6T7ZmI3JlLZ8tahnJUY+IiW+BSYLDYel1eMkw1LqvoiElxsLeEvzSQYDTvOoz2wW49REZuNeZ1Ed1NNzP9UmK6LStoXnVeZ5oJH/BHmfBg2jnow3H9xYFbl8s4vBTJ6IGtsi50dg7b9UP03QuCy6IlSNnEMn7sMJfa5hsCojVtunmnMSDmV4UZUWgYsYv3CdrkkT+lO0jA4GG9HFrFVMEmhEPZ8znJlyRUQUI213vD2uxHNuahGLvzCuUGL2xtrCk7litynu7e7dBxyy0VRrGo8Nw1kMF/ermOZDYNQY/3Cvgr3FuxgH0AAfccqGItUOZN0Vhtg7gLbSfeT6Pz8AoN1tGZxFseODTzaPya7I51veEyUTZ1W3nT/eoghmUczdMlV0L1mDWiOeRUM8L8y2Hm3I+S+37c1qk+ImSVXABFr4OraP7yITAUVNbP567By37S/Jnk+qYeoB9sf6z2f3+ZzNtC0akEVofUGloaSsS96DLxJycqMlJ2lSQnAu+0ADPzDDiUtrVc1qOYOQn9RLertZ+ArUDRbHH7TRJdnBJH+HS+srr/CgPgxQ6wtoQMfR4f/Olpw3XsRTwsP9Xl01Py/1Fqr9c75joJhYu0="
  app:
    develop: techladies-ci-cd-2020-staging