language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm run test
branches:
  only:
  - develop
deploy:
  provider: heroku
  api_key:
    secure: MGV50kJhkLZcOQcY9Ty5FhG7mY2E6ok729ZCJ7CG3fchW4pdMYWWjvFb6bobDBTvjxevQj95oybpMg5GliTFvvQblUbXTmRaCzlFravYRmimeZaHYv0h3EkasE1G6/5A8JtqYgrHIdt4WihTxwe9sjPhdxsyyCM63LAAQi9rPi/5pifsAlPVMJ4dFYMpWbqBmEeSmTIOPTzowV3NI8ASV3351M/WhYb6YJs6ysQ6MbHrBWnX+ocMYJPxGiikwWWiKHypKcyI81VCQQd/RdFXSyHDrlPHN3UBHkf6237DsNznUoAWoM9faK9W3xx/HMwUUWzu31YTNK+PaaM4vUv8G+PXNU6tbqn/VduUlOwDdnbwFiE9I5OcZDXUNzynCZMr5DDUdKM9mR+cXtKMzqrd2Sbf5VI5yBlhO8u1DYqa141PiNTCm9mJeoqy8yzxXAmYX8Q3Upx+QQt1demK/n3+ibb4SAVZoWJd0rwqqQlQEWIgx77lsZLx1aWWQeUE1zufjqZperebBIxyQwhpna/l+HGwSdqHz/IFdYWMcW0P4Hh2uvddWuf91S69pXGPBMc6ZOuGoP1SyZeUoCWdMHQmDe7XbADOCN8ETOuaP23TBPISJ7ppkMimO3JsV+JCAkwrRbtSj3/oatrkkiqfkgSQAA3eR10NriCJEoLkYe+XXXw=
  app:
    develop: techladies-ci-cd-2020-staging
