language: node_js
node_js:
  - 10.13.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - develop
deploy:
  provider: heroku
  api_key:
    secure: "1gK5swh4yDI1t8HkoPgvW0HcpfQpxN92m6rLfQawyKyUHcFITd2MOwArGLirprg+N6IYgKYVnwMcYcAy6gyRt9f7vkbMbR4rWBedmRjkkRR7gLwmmQe7kRhHeVacN4BQXCcylZ2NSMZYWJb1fXvFQpphMruli8X5/RFOS4HPAea4jAEEzrWcFimRHfVwXSfGy5U1KgieiDrzOwzfK7zLd8jG4rtTtG4H78ldgjvBdA1dPbXHyrMWrrINTf5hOAYWfTo0EpKylkkw0GOO66xxVf1qye75IS4osfNCexoshibCjHEwyfHMpxM+XnRe+nhe3YchwC/XS7vYa6WnfgF4fmLKcReq5DvudK3fha/hIAv93X70FPInKDhyXnSIrd2/eOUhPOs9XHDtK1g6uFvAOzjMHvZVBs41K1S+9HQnPnSRMfzCPfE5JuVZO/McTpQAGzXKwkJziAXm0YqC5+kg9UilaceHbmAuSpIeDygnwRGeAAVHHDvA40CGWkaX+PGXlC2S4v8N60hioM/q5+5QIhtquBdfThoerGkV02QZ4kj6uSVx7wIM6xT6hg4dtXX3SmDCGOGZZLoA2djswnDg9fFDHQuzybn/8/NFJJL1oruteHtrQvUgz7UXRkrQkIKALMx1e91H1mLjBfLBuxQrrGmltZ5g9RkR9HvJHsDgktM="
  app:
    develop: techladies-ci-cd-2020-staging
